trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Build and package the app (if needed)
- script: |
    echo "Installing dependencies..."
    npm install
    echo "Building the app..."
    npm run build
    echo "Packaging the app..."
    zip -r app.zip .
  displayName: 'Build and Package the App'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Towards_Az_DevOps'
    appName: 'TestAppCalc'
    package: '$(System.DefaultWorkingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'